from __future__ import annotations

from enum import StrEnum


class PurchaseStatus(StrEnum):
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"
    CHARGEBACK = "CHARGEBACK"
    COMPLETE = "COMPLETE"
    EXPIRED = "EXPIRED"
    NO_FUNDS = "NO_FUNDS"
    OVERDUE = "OVERDUE"
    PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED"
    PRE_ORDER = "PRE_ORDER"
    PRINTED_BILLET = "PRINTED_BILLET"
    PROCESSING_TRANSACTION = "PROCESSING_TRANSACTION"
    PROTESTED = "PROTESTED"
    REFUNDED = "REFUNDED"
    STARTED = "STARTED"
    UNDER_ANALISYS = "UNDER_ANALISYS"
    WAITING_PAYMENT = "WAITING_PAYMENT"


class SubscriptionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DELAYED = "DELAYED"
    CANCELLED_BY_CUSTOMER = "CANCELLED_BY_CUSTOMER"
    CANCELLED_BY_SELLER = "CANCELLED_BY_SELLER"
    CANCELLED_BY_ADMIN = "CANCELLED_BY_ADMIN"
    STARTED = "STARTED"
    OVERDUE = "OVERDUE"


class PaymentType(StrEnum):
    BILLET = "BILLET"
    CASH_PAYMENT = "CASH_PAYMENT"
    CREDIT_CARD = "CREDIT_CARD"
    DIRECT_BANK_TRANSFER = "DIRECT_BANK_TRANSFER"
    DIRECT_DEBIT = "DIRECT_DEBIT"
    FINANCED_BILLET = "FINANCED_BILLET"
    FINANCED_INSTALLMENT = "FINANCED_INSTALLMENT"
    GOOGLE_PAY = "GOOGLE_PAY"
    HOTCARD = "HOTCARD"
    HYBRID = "HYBRID"
    MANUAL_TRANSFER = "MANUAL_TRANSFER"
    PAYPAL = "PAYPAL"
    PAYPAL_INTERNACIONAL = "PAYPAL_INTERNACIONAL"
    PICPAY = "PICPAY"
    PIX = "PIX"
    SAMSUNG_PAY = "SAMSUNG_PAY"
    WALLET = "WALLET"


class CommissionSource(StrEnum):
    PRODUCER = "PRODUCER"
    COPRODUCER = "COPRODUCER"
    AFFILIATE = "AFFILIATE"
    ADDON = "ADDON"


class ProductStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    NOT_APPROVED = "NOT_APPROVED"
    IN_REVIEW = "IN_REVIEW"
    DELETED = "DELETED"
    CHANGES_PENDING_ON_PRODUCT = "CHANGES_PENDING_ON_PRODUCT"


class ProductFormat(StrEnum):
    EBOOK = "EBOOK"
    SOFTWARE = "SOFTWARE"
    MOBILE_APPS = "MOBILE_APPS"
    VIDEOS = "VIDEOS"
    AUDIOS = "AUDIOS"
    TEMPLATES = "TEMPLATES"
    IMAGES = "IMAGES"
    ONLINE_COURSE = "ONLINE_COURSE"
    SERIAL_CODES = "SERIAL_CODES"
    ETICKET = "ETICKET"
    ONLINE_SERVICE = "ONLINE_SERVICE"
    ONLINE_EVENT = "ONLINE_EVENT"
    BUNDLE = "BUNDLE"
    COMMUNITY = "COMMUNITY"
    AGENT = "AGENT"
